/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { BridgeBNB, BridgeBNBInterface } from "../BridgeBNB";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "executor",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "messageId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "status",
        type: "bool",
      },
    ],
    name: "RelayedMessage",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "messageId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "encodedData",
        type: "bytes",
      },
    ],
    name: "UserRequestForAffirmation",
    type: "event",
  },
];

export class BridgeBNB__factory {
  static readonly abi = _abi;
  static createInterface(): BridgeBNBInterface {
    return new utils.Interface(_abi) as BridgeBNBInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BridgeBNB {
    return new Contract(address, _abi, signerOrProvider) as BridgeBNB;
  }
}
