import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Privacy Pools',
  description: 'Generated by createee next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Script src="snarkjs.min.js" strategy="afterInteractive" />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
